name: Update AGH
on:
  push:
    paths-ignore:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build-blocklist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: yarn
        run: |
          yarn install
          yarn run build
      - name: prepare deploy
        run: |
          mkdir build
          cp -rf ./ build/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "AGH"
          git push
