name: Update AGH
on:
  push:
    paths-ignore:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build-blocklist:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm i -g @adguard/hostlist-compiler
      - run: npm ci

      - name: Create local changes
        run: |
          hostlist-compiler -c core.json -o blocklist-agh.txt --verbose
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "AGH"
          git push
